#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FYP.Droid.Resource", IsApplication=true)]

namespace FYP.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int planets_array = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040008
			public const int horizontal_page_margin = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int margin_huge = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int margin_large = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int margin_medium = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int margin_small = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int margin_tiny = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int vertical_page_margin = 2130968585;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_search = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int earth = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_drawer = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int jupiter = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int mars = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mercury = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int neptune = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sample_dashboard_item_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int saturn = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int tile = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int uranus = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int venus = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int accelerometer_text = 2131034124;
			
			// aapt resource value: 0x7f050013
			public const int action_websearch = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int btnAccelerometerView = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int btnAddEmergencyContact = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int btnMyContacts = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int btnMyGoals = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int btnMyHistory = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int btnToggleFallDetection = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int btnUpdateContactDetails = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int content_frame = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int drawer_layout = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int editTextEditContactEmail = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int editTextEditContactName = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int editTextEditContactNumber = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int image = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int left_drawer = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int textView = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int textView10 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int textView12 = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actiivity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_navigation_drawer = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int drawer_list_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditEmergencyContact = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_planet = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int layout1 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MainMenu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Options = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int sample_dashboard_item = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int navigation_drawer = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060006
			public const int action_websearch = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int app_not_available = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int drawer_close = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int drawer_open = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int intro_message = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int navigationdraweractivity_description = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int navigationdraweractivity_title = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int AppTheme = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int Theme_Base = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Theme_Sample = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int Widget = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int Widget_SampleContentContainer = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int Widget_SampleDashboard_Grid = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int Widget_SampleDashboard_Item = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int Widget_SampleDashboard_Item_Description = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int Widget_SampleDashboard_Item_Title = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int Widget_SampleMessage = 2131230725;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
